get:
  summary: Retrieve a deployment description by ID
  tags:
    - Deployments
  parameters:
    - $ref: ../parameters/deploymentId.yaml
    #- $ref: '#/components/parameters/select'
  responses:
    '200':
      description: OK. Successful request
      content:
        application/geo+json:
          schema:
            $ref: ../schemas/geojson/deployment.json
        application/sml+json:
          schema:
            $ref: ../schemas/sensorml/deployment.json
    '400':
      $ref: ../responses/StandardResponses.yaml#/400
    '401':
      $ref: ../responses/StandardResponses.yaml#/401
    '403':
      $ref: ../responses/StandardResponses.yaml#/403
    '404':
      $ref: ../responses/StandardResponses.yaml#/404
    '5XX':
      $ref: ../responses/StandardResponses.yaml#/5XX

put:
  summary: Update a deployment description
  tags:
    - Deployments
  parameters:
    - $ref: ../parameters/deploymentId.yaml
  requestBody:
    content:
      application/geo+json:
        schema:
          $ref: ../schemas/geojson/deployment.json
      application/sml+json:
        schema:
          $ref: ../schemas/sensorml/deployment.json
  responses:
    '204':
      $ref: ../responses/StandardResponses.yaml#/204_PUT
    '400':
      $ref: ../responses/StandardResponses.yaml#/400
    '401':
      $ref: ../responses/StandardResponses.yaml#/401
    '403':
      $ref: ../responses/StandardResponses.yaml#/403
    '404':
      $ref: ../responses/StandardResponses.yaml#/404
    '5XX':
      $ref: ../responses/StandardResponses.yaml#/5XX

delete:
  summary: Delete a deployment resource
  description: |-
    This will delete the deployment and remove it from all collections it is associated to.
  tags:
    - Deployments
  parameters:
    - $ref: ../parameters/deploymentId.yaml
  responses:
    '204':
      $ref: ../responses/StandardResponses.yaml#/204_DELETE
    '400':
      $ref: ../responses/StandardResponses.yaml#/400
    '401':
      $ref: ../responses/StandardResponses.yaml#/401
    '403':
      $ref: ../responses/StandardResponses.yaml#/403
    '404':
      $ref: ../responses/StandardResponses.yaml#/404
    '409':
      $ref: ../responses/StandardResponses.yaml#/409_DELETE
    '5XX':
      $ref: ../responses/StandardResponses.yaml#/5XX