get:
  summary: List deployed systems
  description: |-
    List or search systems deployed during a particular deployment.

    By default, only top level systems are listed (i.e. subsystems are ommitted) unless the "parent" query parameter is set.
  tags:
    - Deployments
  parameters:
    - $ref: ../parameters/deploymentId.yaml
    - $ref: ../parameters/idList.yaml
    - $ref: ../parameters/bbox.yaml
    - $ref: ../parameters/datetime.yaml
    - $ref: ../parameters/geom.yaml
    - $ref: ../parameters/keyword.yaml
    - $ref: ../parameters/parentIdList.yaml
    - $ref: ../parameters/procedureIdList.yaml
    - $ref: ../parameters/foiIdList.yaml
    - $ref: ../parameters/obsPropIdList.yaml
    - $ref: ../parameters/controlPropIdList.yaml
    #- $ref: '#/components/parameters/select'
    - $ref: ../parameters/limit.yaml
  responses:
    '200':
      $ref: ../responses/systemCollection.yaml
    '400':
      $ref: ../responses/StandardResponses.yaml#/400
    '401':
      $ref: ../responses/StandardResponses.yaml#/401
    '403':
      $ref: ../responses/StandardResponses.yaml#/403
    '404':
      $ref: ../responses/StandardResponses.yaml#/404
    '5XX':
      $ref: ../responses/StandardResponses.yaml#/5XX

post:
  summary: Add systems to a deployment
  description: |-
    Add one or more systems to a deployment.
    
    Only links to the system descriptions are provided, allowing them to be hosted on a different server. 
  tags:
    - Deployments
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../schemas/common/links.json
  responses:
    '201':
      $ref: ../responses/StandardResponses.yaml#/201
    '400':
      $ref: ../responses/StandardResponses.yaml#/400
    '401':
      $ref: ../responses/StandardResponses.yaml#/401
    '403':
      $ref: ../responses/StandardResponses.yaml#/403
    '404':
      $ref: ../responses/StandardResponses.yaml#/404
    '5XX':
      $ref: ../responses/StandardResponses.yaml#/5XX