# Simple workflow for bundling schemas into one
name: Bundle schemas

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  bundle_part1:
    runs-on: ubuntu-latest
    name: part1
    steps:

      # first checkout your code
      - name: Checkout
        uses: actions/checkout@v4

      # then use redocly-cli-github-action
      - name: Redocly CLI Bundle Part 1
        uses: fluximus-prime/redocly-cli-github-action@v1
        with:
          args: 'bundle -d api/part1/openapi/openapi-connectedsystems-1.yaml -o openapi-connectedsystems-1.bundle.yaml'

      # blocked by https://github.com/opengeospatial/ogcapi-connected-systems/issues/81 
      #- name: Redocly CLI Bundle Part 2
      #  uses: fluximus-prime/redocly-cli-github-action@v1
      #  with:
      #    args: 'bundle -d api/part2/openapi/openapi-connectedsystems-2.yaml -o openapi-connectedsystems-2.bundle.yaml'

      - name: store generated bundles
        uses: actions/upload-artifact@v4
        with:
          name: store bundles
          path: |
            openapi-connectedsystems-1.bundle.yaml
            openapi-connectedsystems-2.bundle.yaml